version: "3"

services:
  radar-app:
    build: .
    volumes:
      - .:/code
      - /arch/radar:/arch/radar
      # - results:/code/results
    entrypoint:
      - /bin/bash
    stdin_open: true # docker run -i
    tty: true # docker run -t
